services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    volumes:
      - ./recordings:/videos
    restart: always

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "8088:80"
    depends_on:
      - backend
    restart: always

  mediamtx:
    image: docker.1ms.run/bluenviron/mediamtx:1-ffmpeg
    ports:
      - "8888:8888"
    volumes:
      - ./mediamtx.yml:/mediamtx.yml
      - ./recordings:/recordings
    command: /mediamtx.yml
