services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    volumes:
      - /root/mediamtx/recordings:/videos
    restart: always

  frontend:
    extra_hosts:
      - "host.docker.internal:host-gateway" 
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "8088:80"
    depends_on:
      - backend
    restart: always

