services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - 8081:8081
    volumes:
      - /root/mediamtx/recordings:/videos
    restart: always

  frontend:
    network_mode: host
    build:
      context: ./frontend
      dockerfile: Dockerfile
    depends_on:
      - backend
    restart: always

